# Generated by Django 2.2.7 on 2020-11-06 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('niomic', '0002_auto_20201106_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dreamreal',
            name='online',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='niomic.Online'),
        ),
    ]
